-- student 
-- 학번(STUDENT_ID)'20250001', 이름(NAME)'홍길동',키(HEIGHT)164.5, 학과코드(학과테이블참조)
CREATE TABLE STUDENT(
	STUDENT_ID VARCHAR2(15) PRIMARY KEY,
	NAME VARCHAR2(15) NOT NULL,
	HEIGHT NUMBER(3,1),
	DEPT_ID VARCHAR(15) CONSTRAINT DEPARTMENT_DP_ID REFERENCES DEPARTMENT(DEPT_ID) 
); 

-- department
--학과코드(DEPT_ID)'A001', 학과명(DEPT_NAME)'데이터사이언스'
CREATE TABLE DEPARTMENT(
	DEPT_ID VARCHAR2(15) PRIMARY KEY ,
	DEPT_NAME VARCHAR2(45) NOT NULL
);

-- professor
--교수코드(PROF_ID)'P001', 학과코드(학과테이블참조), 교수명(PROF_NAME)'정이안'
CREATE TABLE PROFESSOR(
	PROF_ID VARCHAR2(15) PRIMARY KEY,
	DEPT_ID VARCHAR(15) CONSTRAINT PROFESSOR_DEPARTMENT_DP_ID REFERENCES DEPARTMENT(DEPT_ID),
	PROF_NAME VARCHAR(15) NOT NULL
);

-- subject
--과목코드(SUBJ_ID)'S001', 교수코드(교수테이블참조), 과목명(SUBJ_NAME)'파이썬', 시작일(START_DATE)'2025-03-01', 종료일(END_DATE)
CREATE TABLE SUBJECT(
	SUBJ_ID VARCHAR2(15) PRIMARY KEY,
	PROF_ID VARCHAR2(15) CONSTRAINT SUBJECT_PROFESSOR_PR_ID REFERENCES PROFESSOR(PROF_ID),
	SUBJ_NAME VARCHAR2(60) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
);

-- enroll
-- 수강번호(ENROLL_ID)1234(자동증가), 학번(학생테이블참조), 과목코드(과목테이블참조), 수강일자(ENROLL_DATE)'2025-10-01'
CREATE TABLE ENROLL(
	ENROLL_ID NUMBER(4) PRIMARY KEY,
	STUDENT_ID VARCHAR2(15) CONSTRAINT ENROLL_STUDENT_ST_ID REFERENCES STUDENT(STUDENT_ID),
	SUBJ_ID VARCHAR2(15) CONSTRAINT ENROLL_SUBJECT_SB_ID REFERENCES SUBJECT(SUBJ_ID),
	ENROLL_DATE DATE NOT NULL 
);

-- ENROLL_ID SEQUENCE 생성
CREATE SEQUENCE ENROLL_SEQ;

-- 자릿수 설정 잘못함 수정
ALTER TABLE JAVA_DB.STUDENT MODIFY HEIGHT NUMBER(4,1);

-- INSERT
INSERT INTO DEPARTMENT VALUES('A001','데이터사이언스');
INSERT INTO DEPARTMENT VALUES ('A002','경영학과');
INSERT INTO DEPARTMENT VALUES('A003','데이터과학과');


INSERT
	INTO
	STUDENT(STUDENT_ID , NAME , HEIGHT , DEPT_ID )
VALUES ('20250001',
'홍길동',
165.5,
'A002');
INSERT
	INTO
	STUDENT(STUDENT_ID , NAME , HEIGHT , DEPT_ID )
VALUES ('20250002',
'정서연',
160.3,
'A001');

INSERT INTO PROFESSOR VALUES ('PF-0001','A001','정이안');

INSERT INTO SUBJECT VALUES ('SB-0001','PF-0001','파이썬','2025-03-01','2025-06-30');

INSERT INTO ENROLL VALUES (ENROLL_SEQ.NEXTVAL,'20250001','SB-0001',SYSDATE);
INSERT INTO ENROLL VALUES (ENROLL_SEQ.NEXTVAL,'20250002','SB-0001',SYSDATE);

INSERT
	INTO
	STUDENT(STUDENT_ID , NAME , HEIGHT , DEPT_ID )
VALUES ('20250005',
'최혁',
173,
'A001');

-- spring jpa
insert into stutbl(name) values('유하람');
select * from stutbl;

