-- 1. 사원번호가 176인 사원의 LAST_NAME, 부서번호 정보 조회
SELECT
	e.LAST_NAME ,
	e.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	e.EMPLOYEE_ID = 176;

-- 2. 급여가 12000 이상 되는 직원들의 LAST_NAME, 급여 조회
SELECT
	LAST_NAME ,
	SALARY
FROM
	EMPLOYEES e
WHERE
	e.SALARY >= 12000;

-- 3. 연봉이 5000 ~ 12000 범위가 아닌 사람들의 LAST_NAME, 급여 조회
SELECT
	e.LAST_NAME ,
	e.SALARY
FROM
	EMPLOYEES e
WHERE
	(e.SALARY * 12)<5000
	OR (e.SALARY * 12)>12000;

-- 4. 20번, 50번 부서에 근무하는 사원들의 LAST_NAME, 부서번호를 오름차순으로 조회
SELECT
	e.LAST_NAME ,
	e.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	e.DEPARTMENT_ID IN (20, 50)
ORDER BY
	e.DEPARTMENT_ID ASC,
	e.LAST_NAME ASC;

-- 5. 커미션을 받는 모든 사원들의 LAST_NAME, 급여, 커미션을 조회 / 급여 & 커미션 내림차순 조회
SELECT
	e.LAST_NAME,
	e.SALARY ,
	e.COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	e.COMMISSION_PCT > 0
ORDER BY
	e.SALARY DESC,
	e.COMMISSION_PCT DESC; 

-- 6. 연봉이 2500, 3500, 7000이 아니며, 직무가 SA_REP, ST_CLERK 인 사원조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	(e.SALARY * 12)NOT IN(2500, 3500, 7000)
	AND e.JOB_ID IN ('SA_REP', 'ST_CLERK');

-- 7. 2015/02/20 ~ 2015/05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자 조회
-- 고용일자 내림차순
SELECT
	e.LAST_NAME ,
	e.EMPLOYEE_ID ,
	e.HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	e.HIRE_DATE BETWEEN '2015-02-20' AND '2015-05-01'
ORDER BY
	e.HIRE_DATE DESC;

-- 8. 20번, 50번 부서에 근무하는 사원들 중 연봉이 5000이상 12000이하는 사원의 LAST_NAME, 급여 조회 / 급여의 오름차순 정렬
SELECT
	e.LAST_NAME ,
	e.SALARY
FROM
	EMPLOYEES e
WHERE
	e.DEPARTMENT_ID IN (20, 50)
	AND (e.SALARY * 12) BETWEEN 5000 AND 12000
ORDER BY
	e.SALARY ASC;

-- 9. 연봉이 5000 ~ 12000이 아닌 사원들의 LAST_NAME, 급여 조회 / 급여의 오름차순 정렬
SELECT
	e.LAST_NAME ,
	e.SALARY
FROM
	EMPLOYEES e
WHERE
	e.SALARY NOT BETWEEN 5000 AND 12000
ORDER BY
	e.SALARY ASC;

-- LIKE
-- 10. LAST_NAME에 u가 포합되는 사원들의 사번, LAST_NAME 조회
SELECT
	e.LAST_NAME,
	e.EMPLOYEE_ID
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE '%u%';

-- 11. LAST_NAME에 4번째 글자가 a인 사원들의 LAST_NAME 조회
SELECT
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE '___a%';

-- 12. LAST_NAME에 a 혹은 e 글자가 있는 사원들의 LAST_NAME 조회, LAST_NAME 오름차순
SELECT
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE '%a%'
	OR e.LAST_NAME LIKE '%e%'
ORDER BY e.LAST_NAME ASC;

-- 13. LAST_NAME에 a와 e 글자가 포함된 사원들의 LAST_NAME을 조회하여 LAST_NAME으로 오름차순
SELECT
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE '%a%'
	AND e.LAST_NAME LIKE '%e%'
ORDER BY
	e.LAST_NAME ASC;
-- 강사님 답
SELECT
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE '%a%e%'
	OR e.LAST_NAME LIKE '%e%a%'
ORDER BY
	e.LAST_NAME ASC;

-- is NULL
-- 14. MANAGER ID가 없는 사원들의 LAST_NAME, JOB_ID 조회
SELECT
	e.LAST_NAME ,
	e.JOB_ID
FROM
	EMPLOYEES e
WHERE
	e.MANAGER_ID IS NULL;

-- 15. 직무가 ST_CLERK인 사원이 근무하고 있지 않은 부서 ID 조회
--		단, 부서번호가 NULL인 것은 제외
SELECT
	DISTINCT e.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	e.JOB_ID NOT IN ('ST_CLERK')
	AND e.DEPARTMENT_ID IS NOT NULL;

-- 16. COMMISSION_PCT가 NULL이 아닌 사원들 중 COMMISSION = SALARY * COMMISSION_PCT를 구하여 사번, FIRST_NAME, JOB_ID 조회
SELECT
	e.EMPLOYEE_ID ,
	e.FIRST_NAME ,
	e.JOB_ID,
	SALARY * COMMISSION_PCT AS COMMISSION
FROM
	EMPLOYEES e
WHERE
	e.COMMISSION_PCT IS NOT NULL;

